<a href="https://colab.research.google.com/github/Song-eungi/python_base/blob/main/221114_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B5%90%EC%9E%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
rs = np.random.RandomState(10)

x =10 * rs.rand(5)
y = 2 * x - 1 * rs.rand(5)

x.shape, y.shape

((5,), (5,))

In [ ]:
x

array([7.71320643, 0.20751949, 6.33648235, 7.48803883, 4.98507012])

In [ ]:
y

array([15.20161622,  0.21697612, 11.91243399, 14.80696681,  9.88180043])

In [ ]:
x.shape

(5,)

In [ ]:
x.reshape(-1,1)

array([[7.71320643],
       [0.20751949],
       [6.33648235],
       [7.48803883],
       [4.98507012]])

In [ ]:
x.reshape(-1,1).shape

(5, 1)

In [ ]:
import seaborn as sns
iris_df = sns.load_dataset("iris")
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
X = iris.drop("species", axis=1);X.head(3)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [ ]:
X.shape

(150, 4)

In [ ]:
y = iris["species"] ; y.shape

(150,)

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
X = iris.data
y = iris.target

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### ( 실습 ) 
1. df iris에서 species를 변환 하기 
2. setosa(0), versicolor(1), virginica(2)로 변환하여 
3. new_species 변수를 만들시오

In [ ]:
import seaborn as sns
iris_df = sns.load_dataset("iris")
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
iris_df.head(3)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [ ]:
iris_df["new_01"] = ""
for i in range(0,len(iris_df)):
#     print(iris_df.loc[i, "species"])
#     print(iris_df.iloc[i, 4])
    if iris_df.loc[i, "species"] == "setosa":
        iris_df.loc[i, "new_01"] = 0
    elif iris_df.loc[i, "species"] == "versicolor":
        iris_df.loc[i, "new_01"] = 1
    else:
        iris_df.loc[i, "new_01"] = 2 

sepal_length  sepal_width  petal_length  petal_width species new_01
0           5.1          3.5           1.4          0.2  setosa      0
1           4.9          3.0           1.4          0.2  setosa      0
2           4.7          3.2           1.3          0.2  setosa      0

In [ ]:
iris_df["new_01"] = ""
for i in range(0,len(iris_df)):
    if iris_df.loc[i, "species"] == "setosa":
        iris_df.loc[i, "new_01"] = 0
    elif iris_df.loc[i, "species"] == "versicolor":
        iris_df.loc[i, "new_01"] = 1
    else:
        iris_df.loc[i, "new_01"] = 2 

In [ ]:
iris_df.loc[iris_df["species"] == "setosa","new_02"] = 0
iris_df.loc[iris_df["species"] == "versicolor","new_02"] = 1
iris_df.loc[iris_df["species"] == "virginica","new_02"] = 2

#iris_df.tail(3)

In [ ]:
species_mapping = {"setosa":0, "versicolor":1, "virginica":2}
iris_df["new_03"] = iris_df["species"].map(species_mapping)
iris_df.head(3)

sepal_length  sepal_width  petal_length  petal_width species new_01  \
0           5.1          3.5           1.4          0.2  setosa      0   
1           4.9          3.0           1.4          0.2  setosa      0   
2           4.7          3.2           1.3          0.2  setosa      0   

   new_02  new_03  
0     0.0       0  
1     0.0       0  
2     0.0       0

In [ ]:
y1 = iris_df["new_03"]
y1.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [ ]:
y = iris.target
#y

In [ ]:
X1 = iris_df.iloc[:,:4].values
#X1[:5]

In [ ]:
X = iris.data;X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])